apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
      - name: opa
        image: openpolicyagent/opa:latest
        ports:
        - containerPort: 8181
        volumeMounts:
        - mountPath: /policy
          name: policy
          readOnly: true
  volumes:
  - name: policy
    configMap:
      name: opa-policy
