apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-policy
data:
  policy.rego: |
    package authz

    default allow = false

    allow {
      input.method == "GET"
      input.role == "user"
    }

    allow {
      input.method == "POST"
      input.role == "admin"
    }
